<?php
$productsCollection = $block->getProductsCollection();

//echo "<pre>";print_r($productsCollection->getData());echo "</pre>";
?>

<div class="admin-product-pos-list">
    <?php foreach ($productsCollection as $product): ?>
        <div class="admin-product-card" data-id="<?= $product->getId(); ?>">
            <div class="product-image">
                <img src="<?= $block->getProductImageUrl($product); ?>" width="80" />
            </div>
            <div class="product-content">
                <div class="product-name">
                    <strong><?= $block->escapeHtml($product->getName()) ?></strong>
                </div>
                <div class="product-info">
                    <p>
                        <?= __('SKU: ')?>
                        <span><?= $block->escapeHtml($product->getSku());?></span>
                    </p>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<script>
    require([
        'jquery'
        ],
        function($) {
            const $list = $('.admin-product-pos-list');

            $list.sortable({
                items: '.admin-product-card',
                cursor: 'grabbing',
                tolerance: 'pointer',
                placeholder: 'admin-product-card-placeholder',
                update: function () {
                    $list.find('.admin-product-card').each(function (index) {
                        const id = $(this).data('id');
                        console.log('Product:', id, 'Position:', index);
                    });

                    $.ajax({
                        url: "<?= $block->getUrl('position/category/product') ?>",
                        method: 'POST',
                        dataType: 'json',
                        data: {
                            form_key: window.FORM_KEY,
                            param1: 'test',
                        },
                        success: function (response) {
                            console.log('Position updated successfully for product ID:', id);
                        },
                    });
                }
            });

            $list.disableSelection();
        });
</script>
