<?php
$productsCollection = $block->getProductsCollection();
$categoryId = $block->getCategoryId();

//echo "<pre>";print_r($productsCollection->getData());echo "</pre>";
?>
<div class="admin-product-position-container">
    <div class="admin-product-pos-list">
        <?php foreach ($productsCollection as $product): ?>
            <div class="admin-product-card" data-id="<?= $product->getId(); ?>">
                <div class="product-image">
                    <img src="<?= $block->getProductImageUrl($product); ?>" width="80" />
                </div>
                <div class="product-content">
                    <div class="product-name">
                        <strong><?= $block->escapeHtml($product->getName()) ?></strong>
                    </div>
                    <div class="product-info">
                        <p>
                            <?= __('SKU: ')?>
                            <span><?= $block->escapeHtml($product->getSku());?></span>
                        </p>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="admin-product-position-action">
        <form action="POST" action="" id="product_positions_form">
            <input type="hidden" name="product_positions" id="product_positions" value="" />
            <button class="button primary" type="submit">
                <span><?= __('Update Products Order') ?></span>
            </button>
        </form>
    </div>
</div>

<script>
    require([
        'jquery'
        ],
        function($) {
            const $list = $('.admin-product-pos-list');
            const categoryId = <?= $categoryId ?>;
            let categoryProducts = [];

            $list.sortable({
                items: '.admin-product-card',
                cursor: 'grabbing',
                tolerance: 'pointer',
                placeholder: 'admin-product-card-placeholder',
                update: function () {
                    categoryProducts = [];
                    $list.find('.admin-product-card').each(function (index) {
                        const id = $(this).data('id');
                        console.log('Product:', id, 'Position:', index);
                        categoryProducts.push({
                            "productId": id,
                            "position": index
                        });
                    });
                }
            });
            $list.disableSelection();
            $('#product_positions_form').submit(function(e) {
                e.preventDefault();
                let categoryProductsJson = JSON.stringify(categoryProducts);
                $.ajax({
                    url: "<?= $block->getUrl('position/category/product') ?>",
                    method: 'POST',
                    dataType: 'json',
                    data: {
                        form_key: window.FORM_KEY,
                        cat_prods: categoryProductsJson,
                        category_id: categoryId,
                    },
                    success: function (response) {
                        window.location.reload();
                    },
                });
            })
        });
</script>
