<?php /* ?>
 <pre>
categoryId: <?= (int)($block->getCategoryId() ?? 0) ?>
hasCategory: <?= $block->getCategory() ? 'YES' : 'NO' ?>
</pre>

<?php */ ?>


<?php
$productsCollection = $block->getProductsCollection();

//echo "<pre>";print_r($productsCollection->getData());echo "</pre>";
?>

<div class="admin-product-pos-list">
    <?php foreach ($productsCollection as $product): ?>
        <div class="admin-product-card">
            <div class="product-image">
                <img src="<?= $block->getProductImageUrl($product); ?>" width="80" />
            </div>
            <div class="product-content">
                <div class="product-name">
                    <strong><?= $block->escapeHtml($product->getName()) ?></strong>
                </div>
                <div class="product-info">
                    <p>
                        <?= __('SKU: ')?>
                        <span><?= $block->escapeHtml($product->getSku());?></span>
                    </p>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

